name: Deploy

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Unzip app
        run: unzip loft-app.zip -d site

      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - id: deployment
        uses: actions/deploy-pages@v4

      - name: Slet zip fil
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git rm loft-app.zip
          git commit -m "Slet zip efter deploy"
          git push
